### ISSUE TITLE
Support for angular 7

### ISSUE THREAD

**Issue by joeldenning** [CanopyTax/single-spa-angular#14]
This issue will capture things in progress for getting angular 7 working. Here's the POC / early work on things: https://github.com/joeldenning/angular7-experimentation

- [x] Support `ng build`
- [x] Support `ng serve` (#32)
- [x] Make `ng serve` more useful by opening up the single-spa root config html file (#37)
- [x] ~~Auto generate a root config for people~~ (#29)
- [x] Allow for configuration of webpack externals (#21)
- [x] Have `ng build` call `enableProdMode()`. (See #30)
- [x] Get bundle size down for `ng build` (See #31 and #12)
- [x] Better support and documentation for multiple angular applications (#41)
- [x] SystemJS interop (#44)
- [x] Properly load global styles (#46)
- [x] Navigating between two single-spa applications (#47)
- [x] BrowserAnimationsModule causes problems (#48)

**Comment by joeldenning** [comment]
I created this issue to attempt to contact the angular team in an effort to collaborate with them: https://github.com/angular/angular/issues/28809

**Comment by joeldenning** [comment]
single-spa-angular@3.0.0-beta.3 just released that begins support of `ng build` and schematics

**Comment by joeldenning** [comment]
single-spa-angular@3.0.0-beta.4 now supports `ng serve`, but in a limited way. See #37 for next step with ng-serve.

**Comment by joeldenning** [comment]
single-spa-angular@3.0.0-beta.6 resolves #37 and now `ng serve` is working well

**Comment by joeldenning** [comment]
single-spa-anguluar@3.0.0-beta.9 fixes some issues with `ng serve` on Windows.

**Comment by joeldenning** [comment]
[single-spa-angular@3.0.0-beta.10](https://github.com/CanopyTax/single-spa-angular/releases/tag/v3.0.0-beta.10) reduces bundle size, but had to introduce a breaking change in the process.

**Comment by joeldenning** [comment]
single-spa-angular@3.0.0-beta.11 fixes global styles loading and allows for the user to override webpack configs.

**Comment by joeldenning** [comment]
beta.12 allows for multiple angular applications to be active at once.

**Comment by joeldenning** [comment]
beta.13 has fixes for angular 6 and also removes need for passing in ApplicationRef to single-spa-angular.

**Comment by joeldenning** [comment]
beta.19 makes it easy to use SystemJS and multiple Angular applications.

I am going to close this issue now in favor of just using the github issue queue for any remaining things before single-spa-angular@3 is released as "latest" instead of "beta"
